version: '3.8'

services:
  ftc-event-viewer:
    image: mumtez/ftc-event-viewer:latest
    container_name: ftc-event-viewer
    expose:
      - "80"
    restart: always
    networks:
      - ftc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ftc-network:
    driver: bridge 